title = "Mitten LLC"
baseURL = "/"
languageCode = "en-us"
theme = "airspace-hugo"

# The site's parameters
[params]
  home = "Home"
  
  [menu]

    #[[menu.header]]
    #  weight = 2
    #  name = "Work"
    #  url = "/work"
    #[[menu.header]]
    #  weight = 3
    #  name = "Blog"
    #  url = "/blog"
    #[[menu.header]]
    #  weight = 4
    #  name = "Service"
    #  url = "/service"
    [[menu.header]]
      weight = 5
      name = "Contact"
      url = "/contact"

    #[[menu.footer]]
    #  weight = 1
    #  name = "About us"
    #  url = "#"
    [[menu.footer]]
      weight = 2
      name = "Contact us"
      url = "/contact"
    #[[menu.footer]]
    #  weight = 3
    #  name = "How it works"
    #  url = "#"
    #[[menu.footer]]
    #  weight = 4
    #  name = "Blog"
    #  url = "/blog"
    [[menu.footer]]
      weight = 5
      name = "Privacy"
      url = "/privacy"

  [params.slider]
    enable = true
    title = "A Product Operations Company"
    subtitle = "Product Management for Dept. of Defense, Federal Agencies, and US Government contractors"
    bgImage = "img/leo-fosdal.jpg"
    btnText = "Contact Us"
    url = "/contact"

  [params.wrapper]
    enable = true
    image = "img/beverage-blackboard-coffee.jpg"
    title = "The best from industry, tailored for your organization"
    #italic = "placeholder"
    paragraph = "We work alongside clients to:"
    #benefit1 = "Develop your workforce while building great products"
    #benefit2 = "Improve requirements through user engagement"
    #benefit3 = "Find leverage at scale with a service-based architecture"
      
  [params.blog]
    enable = false
    title = "Get The Latest On What We're doing"
    subtitle = "Catch up with us, anytime and anywhere"

  [params.feature]
    enable = true
    title = "Our Approach"
    italic = "'Start with the customer experience and walk backwards to the technology' -Steve Jobs"
    subtitle = "Start with the customer experience"
    bgImage = "img/paul-hanaoka-285358.jpg"
    content = "From Abbreviated Acquisition (AAP) to Acquisition Category 1 (ACAT 1) Programs, we know how to work with all levels of Government. <br /> <br /> Technology lock-in? We partner with Resource Sponsors, Program Management Offices, and Stakeholders to ensure the user is the primary consideration throughout a Program’s lifecycle. <br /><br /> 100s of system-level requirements? We tailor commercial innovations like the Lean Canvas to provide Mission-driven organizations user and operational value propositions for which to solve. <br /> <br /> Agile development? It may not be right for your organization or situation, but you can still leverage the benefits of the framework with the proper Acquisition or Contract Strategy."
    #[params.feature.button]
    #  caption = "View Works"
    #  url = "#"

  [params.call]
    enable = true
    bgImage = "img/call-to-action-bg.jpg"
    title = "Are you ready for ProductOps?"
    paragraph = "Curious to learn more? Have a product question?"
    [params.call.button]
      url = "https://calendly.com/mitten/intro"
      text = "Let's talk!"

  [params.contact]
    enable = true
    title = "We want to hear from you."
    subtitle = "Don’t just take our word for it. Check out some of our latest work."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "We would like to hear from you."
    #  address = "San Diego, CA"
      email = "Email: ben@mitten.consulting"
      phone = "Phone: 619.905.7866"
    #[params.contact.gmaps]
    #  title = "We Also Count in Google Maps"